name: Pull Request
<<<<<<< HEAD
on:
  pull_request:
  workflow_dispatch:

=======
on: 
  pull_request:
  workflow_dispatch:
  
>>>>>>> 4fee34d373f1a372dd3bf2b0b16efc618e005219
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-24.04
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          save-annotations: true
